import type { Metadata } from "next";
import { Rokkitt } from "next/font/google";
import "./globals.css";

const rokkitt = Rokkitt({
  subsets: ["latin"],
  variable: "--font-rokkitt",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rokkitt.variable} font-sans antialiased`}>{children}</body>
    </html>
  );
}
